In [4]:
import numpy as np

# Step 1: Create an initial list of lists
matrix = [
    [1, 2, 3],
]
matrix.append([4, 5, 6])

# Display the initial matrix
print("Initial matrix:")
for row in matrix:
    print(row)

# Step 2: Append a new row to the list
new_row = [7, 8, 9]
matrix.append(new_row)

# Display the matrix after appending
print("\nMatrix after appending a new row:")
for row in matrix:
    print(row)



Initial matrix:
[1, 2, 3]
[4, 5, 6]

Matrix after appending a new row:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [5]:
# Step 3: Convert the list of lists into a NumPy array
np_matrix = np.array(matrix)

# Step 4: Apply a transpose operation on the NumPy array
transposed_matrix = np_matrix  # .T is the transpose operation in NumPy

# Display the transposed matrix
print("\nTransposed matrix:")
print(transposed_matrix)


Transposed matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
